# Generated by Django 4.1.7 on 2023-04-09 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Макс. 64 символа', max_length=64, null=True, unique=True, verbose_name='название')),
                ('is_published', models.BooleanField(default=True, verbose_name='публикация')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post', verbose_name='картинка')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'db_table': 'blog_categories',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='имя')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('message', models.CharField(max_length=1024, verbose_name='сообщение')),
                ('phone', models.CharField(max_length=64, verbose_name='номер телефона')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата обращения')),
                ('is_published', models.BooleanField(default=False, verbose_name='прочитано')),
            ],
            options={
                'verbose_name': 'контакт',
                'verbose_name_plural': 'База контактов',
                'db_table': 'mainsite_contacts',
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='EmailBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64, verbose_name='эллектронная почта')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата контакта')),
                ('is_published', models.BooleanField(default=False, verbose_name='прочитано')),
            ],
            options={
                'verbose_name': 'адрес почты',
                'verbose_name_plural': 'база эллектронных адресов',
                'db_table': 'mainsite_email_base',
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='FilterAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите есть товар в наличии или он под заказ', max_length=64, null=True, verbose_name='наличие на складе')),
                ('is_published', models.BooleanField(default=True, verbose_name='наличие на складе')),
            ],
            options={
                'verbose_name': 'наличие товара',
                'verbose_name_plural': 'наличие товаров',
                'db_table': 'filter_availability',
            },
        ),
        migrations.CreateModel(
            name='FilterPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Выберите в какой диапазон входит цена товара', max_length=64, null=True, verbose_name='диапазон цены')),
                ('is_published', models.BooleanField(default=True, verbose_name='активировать')),
            ],
            options={
                'verbose_name': 'диапазон цены',
                'verbose_name_plural': 'диапазон цен',
                'db_table': 'filter_price',
            },
        ),
        migrations.CreateModel(
            name='TypeOfPublications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='выберите вид публикации', max_length=64, verbose_name='вид публикации')),
                ('is_published', models.BooleanField(default=False, verbose_name='опубликовать')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'вид публикации',
                'verbose_name_plural': 'вид публикций',
                'db_table': 'type_of_publications',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='название')),
                ('descr', models.TextField(verbose_name='описание')),
                ('is_published', models.BooleanField(default=False, verbose_name='публикация')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post', verbose_name='картинка')),
                ('type_of_publication', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainsite.typeofpublications', verbose_name='вид публикации')),
            ],
            options={
                'verbose_name': 'публикация',
                'verbose_name_plural': 'публикации',
                'db_table': 'mainsite_publication',
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='название')),
                ('descr', models.TextField(verbose_name='описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена товара')),
                ('is_published', models.BooleanField(default=True, verbose_name='публикация')),
                ('novelty', models.BooleanField(default=False, verbose_name='новый товар')),
                ('popularity', models.BooleanField(default=False, verbose_name='популярный товар')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post', verbose_name='картинка')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainsite.category', verbose_name='категория')),
                ('filter_availability', models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainsite.filteravailability', verbose_name='наличие товара')),
                ('filter_price', models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainsite.filterprice', verbose_name='диапазон цены')),
            ],
            options={
                'verbose_name': 'изделие',
                'verbose_name_plural': 'изделия',
                'db_table': 'mainsite_products',
                'ordering': ['date_created'],
            },
        ),
    ]
