# Generated by Django 4.1.4 on 2023-02-03 14:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("mainsite", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeOfPublications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="выберите вид публикации",
                        max_length=64,
                        verbose_name="вид публикации",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="опубликовать"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="URL")),
            ],
            options={
                "verbose_name": "вид публикации",
                "verbose_name_plural": "вид публикций",
                "db_table": "type_of_publications",
            },
        ),
        migrations.AlterField(
            model_name="filterprice",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="активировать"),
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="название")),
                ("descr", models.TextField(verbose_name="описание")),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="публикация"),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="дата создания"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="URL")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="post", verbose_name="картинка"
                    ),
                ),
                (
                    "type_of_publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="mainsite.typeofpublications",
                        verbose_name="вид публикации",
                    ),
                ),
            ],
        ),
    ]
