# Generated by Django 4.1.4 on 2023-02-03 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainsite", "0002_typeofpublications_alter_filterprice_is_published_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publication",
            options={
                "ordering": ["date_created"],
                "verbose_name": "публикация",
                "verbose_name_plural": "публикации",
            },
        ),
        migrations.AlterModelTable(
            name="publication",
            table="mainsite_publication",
        ),
    ]
