# Generated by Django 4.1.4 on 2022-12-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainsite", "0002_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="date_update",
            field=models.DateTimeField(auto_now=True, verbose_name="Время изменения"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Цена товара"
            ),
        ),
    ]
