# Generated by Django 4.1.4 on 2022-12-21 08:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("mainsite", "0003_product_date_update_alter_product_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="имя")),
                ("email", models.EmailField(max_length=254, verbose_name="почта")),
                (
                    "message",
                    models.CharField(max_length=1024, verbose_name="сообщение"),
                ),
                (
                    "phone",
                    models.CharField(max_length=64, verbose_name="номер телефона"),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="дата обращения"
                    ),
                ),
            ],
            options={
                "verbose_name": "контакт",
                "verbose_name_plural": "контакты",
                "db_table": "mainsite_contacts",
                "ordering": ["date_created"],
            },
        ),
    ]
