# Generated by Django 4.1.4 on 2022-12-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainsite", "0004_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="не прочитано"),
        ),
    ]
