# Generated by Django 4.1.4 on 2023-01-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainsite", "0006_product_image_alter_contact_is_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="novelty",
            field=models.BooleanField(default=False, verbose_name="новый товар"),
        ),
    ]
