# Generated by Django 4.1.4 on 2023-01-24 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("mainsite", "0007_product_novelty"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.CharField(max_length=64, verbose_name="эллектронная почта"),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="дата контакта"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="прочитано"),
                ),
            ],
            options={
                "verbose_name": "адрес почты",
                "verbose_name_plural": "база эллектронных адресов",
                "db_table": "mainsite_email_base",
                "ordering": ["date_created"],
            },
        ),
    ]
