# Generated by Django 4.1.4 on 2023-01-24 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainsite", "0008_emailbase"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={
                "ordering": ["date_created"],
                "verbose_name": "контакт",
                "verbose_name_plural": "База контактов",
            },
        ),
        migrations.RenameField(
            model_name="emailbase",
            old_name="email",
            new_name="email2",
        ),
    ]
