# Generated by Django 4.1.4 on 2023-01-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainsite", "0010_rename_email2_emailbase_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="post", verbose_name="картинка"
            ),
        ),
    ]
